quarkus.http.port=8082

# Activer Swagger UI
quarkus.swagger-ui.always-include=true

#quarkus.swagger-ui.path=/swagger-ui

quarkus.smallrye-openapi.info-title=Client Microservice API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API pour la gestion des clients 
quarkus.smallrye-openapi.info-contact-name=Abker


# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=ranim
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Cridiwise

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true
