# =============================================
# APPLICATION GLOBALE
# =============================================
quarkus.http.port=8082
quarkus.log.level=INFO
quarkus.devservices.enabled=false

# Swagger / OpenAPI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true

# =============================================
# DATASOURCE + HIBERNATE CLIENT
# =============================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=ranim
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/clientMicroservice

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.packages=ClientMicroservice.entities
quarkus.hibernate-orm.log.sql=true

# =============================================
# DATASOURCE + HIBERNATE GESTIONNAIRE
# =============================================
quarkus.datasource.gestionnaire.db-kind=postgresql
quarkus.datasource.gestionnaire.username=postgres
quarkus.datasource.gestionnaire.password=ranim
quarkus.datasource.gestionnaire.jdbc.url=jdbc:postgresql://localhost:5432/gestionnaireMicroservice

quarkus.hibernate-orm.gestionnaire.datasource=gestionnaire
quarkus.hibernate-orm.gestionnaire.database.generation=update
quarkus.hibernate-orm.gestionnaire.sql-load-script=import-gestionnaire.sql
quarkus.hibernate-orm.gestionnaire.packages=GestionnaireMicroservice.entities

# =============================================
# JWT CONFIGURATION (sécurisé pour dev)

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=gestionnaire-service
smallrye.jwt.sign.key.location=privateKey.pem


quarkus.http.auth.proactive=false

