-- Insertion des agences (ne fait rien si id_branch existe déjà)
INSERT INTO agences (id_branch, libelle, wording)
VALUES
    ('100', 'SIEGE', 'HEAD OFFICE'),
    ('110', 'INTILAKA', 'INTILAKA'),
    ('120', 'BARCELONE', 'BARCELONE'),
    ('130', 'ARIANA', 'ARIANA'),
    ('140', 'ZAGHOUAN', 'ZAGHOUAN'),
    ('150', 'HAMMAM LIF', 'HAMMAM LIF'),
    ('160', 'NABEUL', 'NABEUL'),
    ('161', 'MENZEL TEMIME', NULL),
    ('170', 'BIZERTE', 'BIZERTE'),
    ('171', 'MATEUR', NULL),
    ('180', 'MANOUBA', 'MANOUBA'),
    ('190', 'MOUROUJ', NULL),
    ('210', 'SOUSSE', 'SOUSSE'),
    ('211', 'HAMEM SOUSSE', 'HAMEM SOUSSE'),
    ('220', 'MAHDIA', 'MAHDIA'),
    ('230', 'MONASTIR', NULL),
    ('310', 'KAIROUAN', 'KAIROUAN'),
    ('311', 'HAFFOUZ', NULL),
    ('312', 'SBIKHA', NULL),
    ('320', 'SIDI BOUZID', 'SIDI BOUZID'),
    ('321', 'Regueb', NULL),
    ('330', 'KASSERINE', 'KASSERINE'),
    ('410', 'BEJA', 'BEJA'),
    ('411', 'MJAZ AL BAB', NULL),
    ('420', 'JENDOUBA', 'JENDOUBA'),
    ('421', 'Bou Salem', NULL),
    ('430', 'EL KEF', 'EL KEF'),
    ('440', 'SILIANA', NULL),
    ('510', 'GABES', 'GABES'),
    ('520', 'MEDENINE', 'MEDENINE'),
    ('521', 'DJERBA', NULL),
    ('530', 'SFAX', 'SFAX'),
    ('531', 'SFAX 2', NULL),
    ('540', 'Agence X', NULL),
    ('610', 'GAFSA', 'GAFSA'),
    ('620', 'KEBILI', NULL),
    ('910', 'CALL CENTER', 'CALL CENTER'),
    ('99999', 'SITE CENTRAL', 'MAIN SITE')
    ON CONFLICT (id_branch) DO NOTHING;